### ISSUE TITLE
Unable to properly switch between printers

### ISSUE THREAD

**Issue by Arakon** [rackrick/MoonWatch#4]
I have 3 printers set up: "VZBot", "Sapphire-V" and "Ender 3".
When switching them on and off, they will appear fine for a short while. 
Eventually, MoonWatch only switches between the last 2 printers, ignoring VZBot.
If the last 2 printers are turned off, it no longer switches back to VZBot and instead shows the clock, while still showing the LED assigned to VZBot as green.
The following error repeatedly appears:
`21:53:48.720 -> Try to switch
21:53:48.720 -> try next printer Sapphire-V(1)
21:53:48.776 -> deserializeJson() failed: NoMemory
21:53:48.815 -> error, printer not reachable. skip.
21:53:48.858 -> idle screen: VZBot
21:53:48.858 -> jsonError
21:54:03.790 -> Try to switch
21:54:03.790 -> try next printer Sapphire-V(1)
21:54:03.836 -> deserializeJson() failed: NoMemory
21:54:03.883 -> error, printer not reachable. skip.
21:54:03.883 -> idle screen: VZBot
21:54:03.883 -> jsonError
`

**Comment by rackrick** [comment]
Hey there... thanks for your feedback. 
For this week I am on the road and not at home. I try to reproduce your issue as soon as I am back at home and and have the hardware available.

**Comment by rackrick** [comment]
https://github.com/rackrick/MoonWatch/releases/tag/0.13-beta
