### ISSUE TITLE
Recent Klipper update seems to keep MoonWatch from working

### ISSUE THREAD

**Issue by Jeff-Haas** [rackrick/MoonWatch#6]
I have a build of MoonWatch that works great, up until recently.  Now when I start it I just see the clock.  I even reflashed it and set it up again, but no change.

There was a different issue I had with a recent update that broke something else, so if you have a minute, please check this out.  Even if the advice is to use KIAUH to roll back to a specific build of Klipper or Moonraker, that would be OK for now.

I expect that you'll figure out they broke something and to tell them what to fix.  I had to roll back one build of Klipper to get the printer to home correctly!

**Comment by rackrick** [comment]
Hey Jeff,

MoonWatch uses only Moonraker to get the printer information. An Klipper Update shouldn't break this.
Pls share your MoonWatch configuration and the versions of Moonraker and Klipper, then I can look into it.

**Comment by Jeff-Haas** [comment]
Here are screenshots of the versions and config.

![image](https://github.com/rackrick/MoonWatch/assets/27331078/dc153a8c-d1bb-4d5a-9855-9111e00cd1d4)

![image](https://github.com/rackrick/MoonWatch/assets/27331078/497feb4f-5c41-45c0-ac03-2b3c726741d2)

**Comment by Jeff-Haas** [comment]
OK, so I don't know what happened, but it's working now.  In the "Host" section above I should have put "ender3.local".  Not sure why it changed.

**Comment by rackrick** [comment]
Thanks for comming back.
Most likely your ender is configured to optain an ip adresse over dhcp. Which can result in an ip change if the printer is offline and the lease expires. Using the hostname covers sudden ip changes.

Glad its working again because I couldn't find any issue on my side 😅

**Comment by Jeff-Haas** [comment]
I think we had a brief power outage that reset things.  Ugh!
