### ISSUE TITLE
Connects to Klipper, shows status then goes to clock when printing starts

### ISSUE THREAD

**Issue by Jeff-Haas** [rackrick/MoonWatch#7]
I set up a new Sovol SV06 on Klipper/Mainsail.  This is a completely new install so all Klipper modules are up-to-date.

Starting Moonwatch, it will connect to the printer and show the status bars, but then when printing starts the clock shows instead.  

What can I look at to help figure this out?

**Comment by rackrick** [comment]
Hey jeff,

usually the clock shows as soon as there is no connection to your moonraker anymore. This sould not happen when you start printing. Can you still access mainsail? Is there maybe a wifi connection issue?

**Comment by Jeff-Haas** [comment]
And of course now it's the next day and everything is working fine.  Sorry to bother you.

Thanks again for a great utility!

**Comment by rackrick** [comment]
no problem as long as it works everyone is happy ;)
